export const NUEVO_USUARIO='NUEVO_USUARIO';
export const USUARIO_EXITOSO='USUARIO_EXITOSO';
export const ERROR_USUARIO='ERROR_USUARIO';

export const AUMENTAR_MONTO='AUMENTAR_MONTO'
export const DISMINUIR_MONTO='DISMINUIR_MONTO'
export const CAMBIAR_SUMA_ASEGURADA='CAMBIAR_SUMA_ASEGURADA'
export const LIMPIAR_STATE_MONTO='LIMPIAR_STATE_MONTO'